### PR TITLE
add in and nin operators

### LINKED ISSUE #8: IN and NOTIN operators
Would be nice to have for arrays

### PR DESCRIPTION
**Pull request by Ashtonian**
resolves #8 

Test currently fails due to deep value check of slices failing. Not sure what the goal is of the check so I'm hesitant to fix it.

### CODE REVIEW

**Comment by Ashtonian** [comment]
@a8m any thoughts on this or assistance on how i should fix the tests?

**Comment by a8m** [comment]
Hey @Ashtonian!
Thanks for your contribution, and sorry for the delayed response. I just returned back from a vacation. 

> any thoughts on this or assistance on how i should fix the tests?

I would be happy to clone this branch and check the test failures. Also, I would like to see integration tests as well (see the `rql/integration` directory). 

I have a different suggestion for how the `ValidateFn/ConvertFn` will deal with slice of params, and I would like to know what do you think about it. 
```go
func (p *parseState) field(f *field, v interface{}) {
  // ...
  fn := f.ValidateFn
  if op == NIN || op == IN {
    fn = validateSlice(fn)
  }
  must(fn(opVal), "invalid datatype for field %q", f.Name)
  // code continues the same
  // ...
}

func validateSlice(fn ValidateFn) ValidateFn {
  return func(v interface{}) error {
     vs, ok := v.([]interface{})
     // handle error.
     for _, v := range vs {
       if err := fn(v); err != nil {
         return err
       }   
     }
   }
}
```
Just to share -  I didn't know that the `$nin` operator exists in MongoDB, and at the start, I thought to implement the `NOT IN` operation with the `"$not": { "$in":  <val> }` syntax. 

This led me to discover that the `$not` operator is missing and it should be added.

**Comment by Ashtonian** [comment]
I was hoping there was a better place to tack it in but didn't see it, looks like that'd be much cleaner ha. I'll update shortly and add some integration tests. Thank you for the response!

**Comment by Ashtonian** [comment]
closing in favor of new pr

**Pull request closed without merging**
